<?php
declare(strict_types=1);require __DIR__.'/config.php';require __DIR__.'/functions.php';require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';$id=(int)($_POST['id']??0);
 if($action==='save'){
  $name=trim((string)($_POST['name']??''));
  if($name===''){set_flash('error','Nama kategori wajib diisi.');redirect('categories');}
  $slug=slugify($name);
  try{if($id){$pdo->prepare('UPDATE categories SET name=?,slug=? WHERE id=?')->execute([$name,$slug,$id]);}else{$pdo->prepare("INSERT INTO categories(name,slug,icon) VALUES(?,?,'')")->execute([$name,$slug]);}set_flash('success',$id?'Kategori berhasil diperbarui.':'Kategori berhasil ditambahkan.');}
  catch(PDOException $e){set_flash('error','Nama kategori tersebut sudah digunakan.');}
 }elseif($action==='delete'){
  $stmt=$pdo->prepare('SELECT COUNT(*) FROM twibbons WHERE category_id=?');$stmt->execute([$id]);$used=(int)$stmt->fetchColumn();
  if($used>0)set_flash('error','Kategori tidak dapat dihapus karena sudah digunakan oleh '.$used.' karya.');
  else{$pdo->prepare('DELETE FROM categories WHERE id=?')->execute([$id]);set_flash('success','Kategori berhasil dihapus.');}
 }
 redirect('categories');
}
$items=$pdo->query('SELECT c.*,COUNT(t.id) total FROM categories c LEFT JOIN twibbons t ON t.category_id=c.id GROUP BY c.id ORDER BY c.name')->fetchAll();$flash=get_flash();
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kategori — Semarakin</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="teal.css"><link rel="stylesheet" href="auth.css"></head><body><header class="site-header"><div class="container nav"><a class="brand" href="./"><span class="brand-mark">S</span>Semarakin</a></div></header><main class="container"><div class="page-head"><span class="eyebrow">Administrator</span><h1 class="page-title">Kategori karya</h1><p class="subtitle">Kelola kategori agar karya lebih mudah ditemukan.</p></div><?php if($flash):?><div class="alert alert-<?=e($flash['type'])?>"><?=e($flash['message'])?></div><?php endif?><div class="creator-studio"><section class="panel"><div class="form-heading"><span class="form-icon">＋</span><div><h2>Kategori baru</h2><p>Gunakan nama yang singkat dan mudah dipahami.</p></div></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><div class="field"><label>Nama kategori</label><input name="name" required maxlength="80" placeholder="Contoh: Lingkungan"></div><button class="btn btn-primary">Tambahkan kategori</button></form></section><section><div class="section-head"><div><h2>Daftar kategori</h2><p><?=count($items)?> kategori tersedia</p></div></div><div class="category-admin-list"><?php foreach($items as $item):?><article class="category-admin-item"><span class="category-symbol" aria-hidden="true"><i></i></span><form method="post" class="category-edit-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><div><label for="category-<?=(int)$item['id']?>">Nama kategori</label><input id="category-<?=(int)$item['id']?>" name="name" value="<?=e($item['name'])?>" required maxlength="80"><small><?=(int)$item['total']?> karya menggunakan kategori ini</small></div><button class="btn btn-secondary btn-sm">Simpan perubahan</button></form><?php if((int)$item['total']===0):?><form method="post" data-confirm="Hapus kategori ini?"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><button class="btn btn-danger btn-sm">Hapus</button></form><?php else:?><button class="btn btn-disabled btn-sm" disabled title="Kategori sedang digunakan">Sedang digunakan</button><?php endif?></article><?php endforeach?></div></section></div></main><footer class="footer">Semarakin · Produk digital dari Apins Digital</footer></body></html>
