<?php
declare(strict_types=1);require __DIR__.'/config.php';require __DIR__.'/functions.php';$user=current_user();$metrics=template_metrics_sql();
$popular=$pdo->query("SELECT t.*,COALESCE(u.name,'Apins Digital') author_name,COALESCE(u.username,'apins-digital') username,COALESCE(u.is_verified,1) is_verified,c.name category_name,c.icon,$metrics FROM twibbons t LEFT JOIN users u ON u.id=t.owner_id LEFT JOIN categories c ON c.id=t.category_id WHERE t.visibility='public' AND t.moderation_status='approved' GROUP BY t.id ORDER BY t.is_featured DESC,(t.use_count+t.download_count+like_count*3) DESC LIMIT 8")->fetchAll();
$categories=$pdo->query("SELECT c.*,COUNT(t.id) total FROM categories c LEFT JOIN twibbons t ON t.category_id=c.id AND t.visibility='public' AND t.moderation_status='approved' GROUP BY c.id ORDER BY total DESC,c.name LIMIT 8")->fetchAll();
$creators=$pdo->query("SELECT u.id,u.name,u.username,u.bio,u.is_verified,COUNT(DISTINCT t.id) works,COUNT(DISTINCT f.follower_id) followers FROM users u JOIN twibbons t ON t.owner_id=u.id AND t.visibility='public' AND t.moderation_status='approved' LEFT JOIN follows f ON f.creator_id=u.id WHERE u.status='active' GROUP BY u.id ORDER BY followers DESC,works DESC LIMIT 4")->fetchAll();
$stats=$pdo->query("SELECT COUNT(*) works,COALESCE(SUM(use_count),0) supports,COALESCE(SUM(download_count),0) downloads FROM twibbons WHERE visibility='public' AND moderation_status='approved'")->fetch();
$articles=$pdo->query("SELECT * FROM articles WHERE status='published' ORDER BY created_at DESC LIMIT 3")->fetchAll();
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Semarakin adalah ruang kreator Indonesia untuk membuat, menemukan, dan membagikan kampanye visual serta twibbon gratis."><meta name="robots" content="index,follow,max-image-preview:large"><meta name="author" content="Apins Digital"><meta name="theme-color" content="#0f8f83"><link rel="canonical" href="https://bingkaiin.apinsdigital.my.id/"><meta property="og:type" content="website"><meta property="og:locale" content="id_ID"><meta property="og:site_name" content="Semarakin"><meta property="og:title" content="Semarakin — Ruang Kampanye Kreatif Indonesia"><meta property="og:description" content="Temukan karya kreator, dukung gerakan, dan buat kampanye visualmu sendiri."><meta property="og:url" content="https://bingkaiin.apinsdigital.my.id/"><meta name="twitter:card" content="summary_large_image"><title>Semarakin — Ruang Kampanye Kreatif Indonesia</title><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'WebApplication','name'=>'Semarakin','url'=>'https://bingkaiin.apinsdigital.my.id/','applicationCategory'=>'DesignApplication','description'=>'Platform komunitas kampanye visual dan twibbon Indonesia.','creator'=>['@type'=>'Organization','name'=>'Apins Digital','url'=>'https://apinsdigital.my.id/']],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="teal.css"><link rel="stylesheet" href="auth.css"></head><body><header class="site-header"><div class="container nav"><a class="brand" href="./"><span class="brand-mark">S</span>Semarakin</a></div></header><main>
<section class="hero marketplace-hero"><div class="container hero-market-grid"><div><span class="eyebrow">✦ Produk kreatif dari Apins Digital</span><h1>Temukan gerakan.<br><span class="gradient-text">Ikut semarakkan.</span></h1><p>Ruang bagi kreator dan komunitas Indonesia untuk membuat kampanye visual, menjangkau audiens, dan merayakan momen bersama.</p><div class="hero-actions"><?php if($user):?><a class="btn btn-primary" href="dashboard">Buat karya baru →</a><?php else:?><a class="btn btn-primary" href="register">Mulai berkarya →</a><?php endif?><a class="btn btn-secondary" href="explore">Jelajahi karya</a></div></div><div class="hero-community-card"><span>Komunitas hari ini</span><strong><?=compact_number((int)$stats['supports'])?></strong><p>dukungan diberikan melalui karya kreator.</p><div><b><?=compact_number((int)$stats['works'])?> karya</b><b><?=compact_number((int)$stats['downloads'])?> unduhan</b></div></div></div></section>
<section class="section category-section"><div class="container"><div class="section-head"><div><span class="eyebrow">Jelajahi momen</span><h2>Kategori untuk setiap cerita.</h2></div><a href="explore">Lihat semua →</a></div><div class="home-categories"><?php foreach($categories as $cat):?><a href="explore?category=<?=e($cat['slug'])?>"><span class="category-symbol" aria-hidden="true"><i></i></span><strong><?=e($cat['name'])?></strong><small><?=(int)$cat['total']?> karya</small></a><?php endforeach?></div></div></section>
<section class="section" id="templates"><div class="container"><div class="section-head"><div><span class="eyebrow">Sedang ramai</span><h2>Karya pilihan komunitas.</h2><p>Dinilai dari penggunaan, apresiasi, dan kurasi.</p></div><a href="explore?sort=popular">Selengkapnya →</a></div><div class="social-grid"><?php foreach($popular as $item):require __DIR__.'/template-card.php';endforeach?></div><?php if(!$popular):?><div class="empty">Karya publik segera hadir.</div><?php endif?></div></section>
<?php if($creators):?><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Kreator pilihan</span><h2>Kenali orang di balik karya.</h2></div></div><div class="creator-cards"><?php foreach($creators as $creator):?><a href="creator/<?=e($creator['username'])?>"><span class="creator-avatar"><?=e(strtoupper(mb_substr($creator['name'],0,1)))?></span><div><h3><?=e($creator['name'])?> <?=$creator['is_verified']?'✓':''?></h3><p><?=e($creator['bio']?:'Kreator kampanye visual di Semarakin.')?></p><small><?=compact_number((int)$creator['followers'])?> pengikut · <?=(int)$creator['works']?> karya</small></div></a><?php endforeach?></div></div></section><?php endif?>
<section class="section"><div class="container"><div class="how-panel"><div><span class="eyebrow">Mudah digunakan</span><h2>Tiga langkah untuk ikut bergerak.</h2></div><ol><li><b>01</b><span><strong>Pilih karya</strong>Temukan kampanye yang ingin kamu dukung.</span></li><li><b>02</b><span><strong>Sesuaikan foto</strong>Atur posisi foto langsung dari browser.</span></li><li><b>03</b><span><strong>Unduh & bagikan</strong>Rayakan momen bersama komunitasmu.</span></li></ol></div></div></section>
<?php if($articles):?><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Wawasan</span><h2>Ide untuk gerakan berikutnya.</h2></div></div><div class="article-grid"><?php foreach($articles as $article):?><a href="article/<?=e($article['slug'])?>"><small><?=date('d M Y',strtotime($article['created_at']))?></small><h3><?=e($article['title'])?></h3><p><?=e($article['excerpt'])?></p><strong>Baca artikel →</strong></a><?php endforeach?></div></div></section><?php endif?>
<section class="section"><div class="container"><div class="home-cta"><span class="eyebrow">Gratis untuk memulai</span><h2>Karyamu bisa menjadi awal gerakan besar.</h2><p>Buat profil kreator, unggah desain, dan tumbuhkan komunitasmu.</p><a class="btn btn-secondary" href="<?=$user?'dashboard':'register'?>"><?=$user?'Buka studio kreator':'Buat akun gratis'?> →</a></div></div></section></main><footer class="footer"><div class="container"><strong>Semarakin</strong> · Produk digital dari Apins Digital · © <?=date('Y')?></div></footer></body></html>
