<?php
declare(strict_types=1);require __DIR__.'/config.php';require __DIR__.'/functions.php';require_login();$user=current_user();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 try{
  if($action==='profile'){$name=trim((string)($_POST['name']??''));$email=strtolower(trim((string)($_POST['email']??'')));if(mb_strlen($name)<2||mb_strlen($name)>100)throw new RuntimeException('Nama harus terdiri dari 2–100 karakter.');if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Alamat email tidak valid.');$stmt=$pdo->prepare('SELECT COUNT(*) FROM users WHERE email=? AND id<>?');$stmt->execute([$email,$user['id']]);if((int)$stmt->fetchColumn()>0)throw new RuntimeException('Email sudah digunakan akun lain.');$pdo->prepare('UPDATE users SET name=?,email=? WHERE id=?')->execute([$name,$email,$user['id']]);$_SESSION['user']['name']=$name;$_SESSION['user']['email']=$email;flash('success','Informasi profil berhasil diperbarui.');}
  elseif($action==='password'){$stmt=$pdo->prepare('SELECT password FROM users WHERE id=?');$stmt->execute([$user['id']]);$hash=$stmt->fetchColumn();$current=(string)($_POST['current_password']??'');$new=(string)($_POST['new_password']??'');if(!password_verify($current,$hash))throw new RuntimeException('Password saat ini tidak sesuai.');if(strlen($new)<8)throw new RuntimeException('Password baru minimal 8 karakter.');if($new!==($_POST['password_confirmation']??''))throw new RuntimeException('Konfirmasi password baru tidak sama.');$pdo->prepare('UPDATE users SET password=? WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),$user['id']]);flash('success','Password berhasil diperbarui.');}
 }catch(Throwable $e){flash('error',$e->getMessage());}header('Location: profile');exit;}
$flash=pull_flash();$user=current_user();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Profil — Bingkaiin</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="teal.css"><link rel="stylesheet" href="auth.css"></head><body><header class="site-header"><div class="container nav"><a class="brand" href="./"><span class="brand-mark">B</span>Bingkaiin</a></div></header><main class="container profile-page"><div class="page-head"><span class="eyebrow">Pengaturan akun</span><h1 class="page-title" style="margin-top:12px">Profil saya</h1><p class="subtitle">Kelola identitas dan keamanan akun Anda.</p></div><?php if($flash):?><div class="alert alert-<?=e($flash['type'])?>"><?=e($flash['message'])?></div><?php endif?><div class="profile-grid"><aside class="profile-summary"><div class="avatar"><?=e(strtoupper(mb_substr($user['name'],0,1)))?></div><h2><?=e($user['name'])?></h2><p><?=e($user['email'])?></p><span class="visibility <?=$user['role']==='admin'?'visibility-public':'visibility-unlisted'?>"><?=e(ucfirst($user['role']))?></span></aside><div class="profile-forms"><section class="panel"><div class="form-heading"><span class="form-icon">✦</span><div><h2>Informasi pribadi</h2><p>Nama ini tampil pada dashboard Anda.</p></div></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="profile"><div class="field"><label for="name">Nama lengkap</label><input id="name" name="name" value="<?=e($user['name'])?>" required maxlength="100"></div><div class="field"><label for="email">Alamat email</label><input id="email" name="email" type="email" value="<?=e($user['email'])?>" required></div><button class="btn btn-primary">Simpan perubahan</button></form></section><section class="panel"><div class="form-heading"><span class="form-icon">●</span><div><h2>Ubah password</h2><p>Gunakan minimal 8 karakter yang sulit ditebak.</p></div></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="password"><div class="field"><label for="current_password">Password saat ini</label><input id="current_password" name="current_password" type="password" required autocomplete="current-password"></div><div class="field"><label for="new_password">Password baru</label><input id="new_password" name="new_password" type="password" minlength="8" required autocomplete="new-password"></div><div class="field"><label for="password_confirmation">Konfirmasi password baru</label><input id="password_confirmation" name="password_confirmation" type="password" minlength="8" required autocomplete="new-password"></div><button class="btn btn-primary">Perbarui password</button></form></section></div></div></main><footer class="footer">Bingkaiin · Produk digital dari Apins Digital</footer></body></html>
